lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - assets/nf-core-fspassemblypipeline_logo_light.png
    - docs/images/nf-core-fspassemblypipeline_logo_light.png
    - docs/images/nf-core-fspassemblypipeline_logo_dark.png
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Lia Obinu, Niall Garvey, Wu Huang
  description: Genome assembly pipeline for the Fungarium Sequencing Project, designed
    to process and assemble genomic data from fungal species, enabling high-quality
    reference genomes for research and biodiversity studies.
  force: false
  is_nfcore: true
  name: fspassemblypipeline
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - gpu
  version: 1.0.0dev
